//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidProject.EF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CollectRequest
    {
        [Required]
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Quantity { get; set; }
        [Required]
        public System.DateTime RequestDate { get; set; }
        [Required]
        public System.DateTime MaximumPreserveTime { get; set; }
        [Required]
        public string Image { get; set; }
        [Required]
        public string Status { get; set; }= "Pending";
        public int LoginID { get; set; }
        public string RestaurantName { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Login Login { get; set; }
    }
}
